version: '3.1'

services:
    db:
        image: mysql:5.7
        env_file:
            - ./docker/db/.env
        volumes:
            - ./docker/db/data:/var/lib/mysql:rw
            - ./docker/db/conf.d:/etc/mysql/my.cnf:ro
        ports:
            - "3306:3306"

    php:
        build: ./docker/php/7.2/
        volumes:
            - ./docker/php/app.ini:/usr/local/etc/php/conf.d/docker-php-ext-app.ini:ro
            - ./docker/logs/app:/var/www/app/var/log:cached
            - .:/var/www/app:cached
        working_dir: /var/www/app
        links:
            - db
        env_file:
            - ./docker/php/.env

    webserver:
        image: nginx:1
        depends_on:
            - php
        volumes:
            - ./docker/webserver/app.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/logs/webserver/:/var/log/nginx:cached
            - .:/var/www/app:ro
        ports:
            - "80:80"

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"

    adminer:
        build: ./docker/adminer/
        restart: always
        ports:
          - "8080:8080"

    elasticsearch:
        image: elasticsearch:7.3.0
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"

    kibana:
        image: kibana:7.3.0
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        environment:
            - "RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1024MiB"
        ports:
            - "5672:5672"
            - "15672:15672"

    mercure:
        image: dunglas/mercure:latest
        environment:
            - "JWT_KEY=D0c!<3r-MerCure-$ecRe|"
            - "DEMO=1"
            - "ALLOW_ANONYMOUS=1"
            - "DEBUG=1"
            - "CORS_ALLOWED_ORIGINS=*"
            - "PUBLISH_ALLOWED_ORIGINS=http://webserver"
        ports:
            - "3000:3000"

volumes:
    elasticsearch-data: {}
    rabbitmq-data: {}